### PR TITLE
Change tabs to spaces

### PR DESCRIPTION
**Pull request by runekri3**
Change all tabs to 4 spaces.

### CODE REVIEW

**Comment by BrianOstrander** [comment]
I'm away from my computer at the moment, but I'll pull this once I've had a chance to sit down and run it!

**Comment by runekri3** [comment]
Alright, to be fair, I didn't run it myself since I didn't bother setting up a database right now but it should work fine. There is quite a lot of formatting that doesn't quite follow [PEP 8](https://www.python.org/dev/peps/pep-0008/). I could reformat the whole project to abide with the standards but I wanna know, what do you think about it? For example setupLogging would usually be named setup_logging in Python.

**Comment by BrianOstrander** [comment]
I understand, a standard is a standard. If you're interested in refactoring it to follow PEP 8 I'm more than happy to follow that in the future!

Is there anything I could do to make the DB setup easier? I think there's a way to use sqlAlchemy with a local SQLite DB for testing. I could also include the MySQL table formatting in the repo.

**Comment by runekri3** [comment]
Yeah, that would work good. You could also generate the tables if they don't exist at startup. I'm pretty sure that's possible with SQLAlchemy.

If you want, we could talk somewhere else than on github; e-mail, skype etc, you have my reddit and e-mail so you can reply there.

**Comment by BrianOstrander** [comment]
I've invited your email to a slack I created.

**Pull request merged**
